# Generated by Django 6.0 on 2025-12-30 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('usage_title', models.CharField(blank=True, max_length=120)),
                ('usage_type', models.CharField(blank=True, choices=[('language', 'Language'), ('tool', 'Tool'), ('other', 'Other')], max_length=20)),
                ('usage_items', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
