# Generated by Codex on 2025-12-30

from django.db import migrations


def _ensure_list(value):
    if isinstance(value, list):
        return value
    if value is None:
        return []
    return [value]


def seed_projects(apps, schema_editor):
    Project = apps.get_model("pages", "Project")
    if Project.objects.exists():
        return

    try:
        from pages.data import PROJECTS
    except Exception:
        return

    for idx, project in enumerate(PROJECTS, start=1):
        name = project.get("name", "").strip()
        if not name:
            continue
        Project.objects.create(
            name=name,
            summary=project.get("summary", ""),
            link=project.get("link", ""),
            tech_stack=_ensure_list(project.get("tech_stack")),
            details=_ensure_list(project.get("details")),
            highlights=_ensure_list(project.get("highlights")),
            note=project.get("note", ""),
            usage_title=project.get("usage_title", ""),
            usage_type=project.get("usage_type", ""),
            usage_items=_ensure_list(project.get("usage_items")),
            order=idx,
        )


def unseed_projects(apps, schema_editor):
    Project = apps.get_model("pages", "Project")
    try:
        from pages.data import PROJECTS
    except Exception:
        return

    names = [project.get("name", "").strip() for project in PROJECTS]
    Project.objects.filter(name__in=[name for name in names if name]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_projects, unseed_projects),
    ]
