# Generated by Codex to seed profile data for jimin.

from django.conf import settings
from django.db import migrations


def seed_profile(apps, schema_editor):
    user_label, user_model = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_label, user_model)
    Profile = apps.get_model("pages", "Profile")

    try:
        user = User.objects.get(username="jimin")
    except User.DoesNotExist:
        return

    defaults = {
        "name": "\ubc15\uc9c0\ubbfc",
        "headline": "\uc804\uc8fc\ube44\uc804\ub300\ud559\uad50 \ucef4\ud4e8\ud130\uc815\ubcf4\uacfc 1\ud559\ub144",
        "summary": "C, Python, Java\ub97c \ub2e4\ub8f0 \uc218 \uc788\uc2b5\ub2c8\ub2e4.",
        "email": "vision202518015@gmail.com",
        "github": "https://github.com/jimin-vision",
        "resume": "",
        "focus_language": "C, Python, Java",
        "focus_interest": "\uac8c\uc784, \uc74c\uc545\uac10\uc0c1",
        "focus_goal": "\ubc31\uc5d4\ub4dc \uac1c\ubc1c\uc790",
    }

    profile, _ = Profile.objects.get_or_create(user=user, defaults=defaults)
    updated = False
    for key, value in defaults.items():
        if not getattr(profile, key):
            setattr(profile, key, value)
            updated = True
    if updated:
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(seed_profile, migrations.RunPython.noop),
    ]
